blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/rezer-bleede/dbt-Workbench/discussions
    about: "Use discussions for questions, brainstorming, or design talks."
